# Generated by Django 5.2.17 on 2026-10-05 06:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_create_superuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_achievements', to=settings.AUTH_USER_MODEL),
        ),
    ]
